### ISSUE TITLE
Plugin is breaking activity deletion (adhoc task)

### ISSUE THREAD

**Issue by vancouverdeveloper** [blackboard-open-source/moodle-filter_ally#15]
The plugin is preventing the completion of activity deletion process .

A teacher has deleted a bunch of activities from her course, but they do not delete. Instead she sees them still, and gets the onscreen message “Activity Deletion in progress” attached). It’s been in that state for days, apparently.

I caught that in our moodle log

Adhoc task failed: core_course\task\course_delete_modules,Coding error detected, it must be fixed by a programmer: The course module 791661 could not be deleted. #0 /our/moodle//lib/modinfolib.php(2232): course_modinfo->get_cm(791661)
#1 /our/moodle//admin/tool/ally/lib.php(89): get_course_and_cm_from_cmid('791661', NULL, '6181')
**#2 **_/our/moodle//course/lib.php(1185): tool_ally_pre_course_module_delete(Object(stdClass))_****
#3 /our/moodle//course/classes/task/course_delete_modules.php(66): course_delete_module('791661')
#4 /our/moodle//lib/cronlib.php(185): core_course\task\course_delete_modules->execute()
#5 /our/moodle//lib/cronlib.php(74): cron_run_inner_adhoc_task(Object(core_course\task\course_delete_modules))
#6 /our/moodle//admin/cli/cron.php(61): cron_run()

**Comment by samchaffee** [comment]
Hi, thanks for the report. We've fixed the issue in our 3.6 version of the Ally admin tool plugin which we will tag in mid-July. The fix is currently in the master branch of the moodle-tool_ally repo if you need it before then. See https://github.com/blackboard-open-source/moodle-tool_ally/commit/6e2bdcf564bbcf61eebb0ccc2498b1e9e0e91941
